
CREATE TABLE user (
	ID_User INT NOT NULL UNIQUE AUTO_INCREMENT,
	username VARCHAR(50) NOT NULL UNIQUE,
	passwordHash VARCHAR(255) NOT NULL,
	description TEXT NOT NULL DEFAULT 'This user hasn\'t set their description yet.',
	trustScore INT NOT NULL DEFAULT 5,
	joinDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	picture VARCHAR(50) NOT NULL DEFAULT '../assets/img/profilepic/placeholder.png'
);

CREATE TABLE article (
	ID_Article INT NOT NULL UNIQUE AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL UNIQUE,
	helpfulness INT NOT NULL DEFAULT 0,
	author_User_ID INT,
	timeCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	
	FOREIGN KEY (author_User_ID)
	REFERENCES user(ID_User)
	ON UPDATE CASCADE
	ON DELETE SET NULL
);

CREATE TABLE post (
	ID_Post INT NOT NULL UNIQUE AUTO_INCREMENT,
	lang_Article_ID INT NOT NULL,
	creator_User_ID INT,
	contentTitle VARCHAR(50) NOT NULL,
	contentText TEXT,
	image VARCHAR(50),
	score INT NOT NULL DEFAULT 0,
	timeCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),

	FOREIGN KEY (lang_Article_ID)
	REFERENCES article(ID_Article)
	ON UPDATE CASCADE
	ON DELETE CASCADE,

	FOREIGN KEY (creator_User_ID)
	REFERENCES user(ID_User)
	ON UPDATE CASCADE
	ON DELETE SET NULL
);

CREATE TABLE comment (
	ID_Comment INT NOT NULL UNIQUE AUTO_INCREMENT,
	thread_Post_ID INT NOT NULL,
	parent_Comment_ID INT,
	creator_User_ID INT,
	contentText TEXT NOT NULL,
	score INT NOT NULL DEFAULT 0,
	timeCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	
	FOREIGN KEY (thread_Post_ID)
	REFERENCES post(ID_Post)
	ON UPDATE CASCADE
	ON DELETE CASCADE,

	FOREIGN KEY (parent_Comment_ID)
	REFERENCES comment(ID_Comment)
	ON UPDATE CASCADE
	ON DELETE CASCADE,

	FOREIGN KEY (creator_User_ID)
	REFERENCES user(ID_User)
	ON UPDATE CASCADE
	ON DELETE SET NULL
);